###
GET localhost:8080/me?format=csv

###
GET localhost:8080/me
Accept: text/csv

### 멤버생성
POST localhost:8080/members
Content-Type: application/json
Accept-Language: ko-KR

{
  "id" : "sgs0630123",
  "name" : "신건수",
  "age" : 50,
  "role" : "ADMIN",
  "class" : "A"
}

### 멤버 전체 조회
GET localhost:8080/members

### 멤버 조회
GET localhost:8080/members/sgs0630

### 멤버 삭제
DELETE localhost:8080/members/sgs0630

### resttemplate
POST localhost:8080/send-message
Content-Type: application/json

{
  "channel": "B",
  "text": "Bzzz"
}
